Traceback (most recent call last):
  File "f:\file_comparison_tool\test.py", line 51, in <module>
    discrepancy_data = compare_data(data_dict1, data_dict2)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\file_comparison_tool\test.py", line 37, in compare_data
    discrepancy_now = [trade_id] + list(row1.values()) + list(row2.values())
                                        ^^^^^^^^^^^^^
TypeError: 'numpy.ndarray' object is not callable
